-- Sprint 2F-A — Metadatafundament hitlijsten
-- Adds managed metadata dimensions for omroep/zender and hitlijst period.
-- Idempotent: safe to run multiple times.

CREATE TABLE IF NOT EXISTS public.omroepen (
  omroep_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  omroep_code varchar(40) NOT NULL UNIQUE,
  omroep_naam varchar(150) NOT NULL UNIQUE,
  omroep_land varchar(2),
  omroep_actief boolean NOT NULL DEFAULT true,
  omroep_opmerking text,
  sort_order integer NOT NULL DEFAULT 999,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.hitlijst_perioden (
  periode_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periode_code varchar(40) NOT NULL UNIQUE,
  periode_naam varchar(150) NOT NULL UNIQUE,
  periode_type varchar(30) NOT NULL,
  start_jaar integer,
  eind_jaar integer,
  actief boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 999,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now(),
  CONSTRAINT hitlijst_perioden_type_chk CHECK (periode_type IN ('UNKNOWN','DECADE','ALLTIME','YEAR','THEME','GENRE','OTHER')),
  CONSTRAINT hitlijst_perioden_range_chk CHECK (
    (start_jaar IS NULL AND eind_jaar IS NULL) OR
    (start_jaar IS NOT NULL AND eind_jaar IS NOT NULL AND start_jaar <= eind_jaar)
  )
);

INSERT INTO public.omroepen (omroep_code, omroep_naam, omroep_land, omroep_actief, omroep_opmerking, sort_order)
VALUES
  ('ONBEKEND', 'Onbekend / nog te bepalen', NULL, true, 'Defaultwaarde voor bestaande of nog niet geclassificeerde imports.', 0),
  ('NPO_RADIO_2', 'NPO Radio 2', 'NL', true, NULL, 10),
  ('NPO_3FM', 'NPO 3FM', 'NL', true, NULL, 15),
  ('RADIO_VERONICA', 'Radio Veronica', 'NL', true, NULL, 20),
  ('RADIO_10', 'Radio 10', 'NL', true, NULL, 30),
  ('RADIO_538', 'Radio 538', 'NL', true, NULL, 40),
  ('QMUSIC_NL', 'Qmusic Nederland', 'NL', true, NULL, 50),
  ('SKY_RADIO', 'Sky Radio', 'NL', true, NULL, 55),
  ('KRO_NCRV', 'KRO-NCRV', 'NL', true, NULL, 56),
  ('AVROTROS', 'AVROTROS', 'NL', true, NULL, 57),
  ('VRT_RADIO_2', 'VRT Radio 2', 'BE', true, NULL, 60),
  ('STUDIO_BRUSSEL', 'Studio Brussel', 'BE', true, NULL, 70),
  ('RADIO_1_BE', 'Radio 1 België', 'BE', true, NULL, 75),
  ('BBC_RADIO_1', 'BBC Radio 1', 'GB', true, NULL, 80),
  ('BBC_RADIO_2', 'BBC Radio 2', 'GB', true, NULL, 90)
ON CONFLICT (omroep_code) DO UPDATE
SET omroep_naam = EXCLUDED.omroep_naam,
    omroep_land = EXCLUDED.omroep_land,
    omroep_actief = EXCLUDED.omroep_actief,
    omroep_opmerking = EXCLUDED.omroep_opmerking,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();

INSERT INTO public.hitlijst_perioden (periode_code, periode_naam, periode_type, start_jaar, eind_jaar, actief, sort_order)
VALUES
  ('ONBEKEND', 'Onbekend / nog te bepalen', 'UNKNOWN', NULL, NULL, true, 0),
  ('50S', 'Jaren 50', 'DECADE', 1950, 1959, true, 10),
  ('60S', 'Jaren 60', 'DECADE', 1960, 1969, true, 20),
  ('70S', 'Jaren 70', 'DECADE', 1970, 1979, true, 30),
  ('80S', 'Jaren 80', 'DECADE', 1980, 1989, true, 40),
  ('90S', 'Jaren 90', 'DECADE', 1990, 1999, true, 50),
  ('00S', 'Jaren 00', 'DECADE', 2000, 2009, true, 60),
  ('10S', 'Jaren 10', 'DECADE', 2010, 2019, true, 70),
  ('20S', 'Jaren 20', 'DECADE', 2020, 2029, true, 80),
  ('ALLTIME', 'All-time greatest', 'ALLTIME', NULL, NULL, true, 90),
  ('JAARLIJST', 'Jaarlijst', 'YEAR', NULL, NULL, true, 100),
  ('THEMA', 'Themalijst', 'THEME', NULL, NULL, true, 110),
  ('GENRE', 'Genrelijst', 'GENRE', NULL, NULL, true, 120),
  ('OVERIG', 'Overig', 'OTHER', NULL, NULL, true, 999)
ON CONFLICT (periode_code) DO UPDATE
SET periode_naam = EXCLUDED.periode_naam,
    periode_type = EXCLUDED.periode_type,
    start_jaar = EXCLUDED.start_jaar,
    eind_jaar = EXCLUDED.eind_jaar,
    actief = EXCLUDED.actief,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();

ALTER TABLE public.staging_hitlijsten
  ADD COLUMN IF NOT EXISTS omroep_key integer,
  ADD COLUMN IF NOT EXISTS periode_key integer;

ALTER TABLE public.hitlijsten
  ADD COLUMN IF NOT EXISTS omroep_key integer,
  ADD COLUMN IF NOT EXISTS periode_key integer;

DO $$
DECLARE
  v_unknown_omroep integer;
  v_unknown_periode integer;
BEGIN
  SELECT omroep_key INTO v_unknown_omroep FROM public.omroepen WHERE omroep_code = 'ONBEKEND';
  SELECT periode_key INTO v_unknown_periode FROM public.hitlijst_perioden WHERE periode_code = 'ONBEKEND';

  UPDATE public.staging_hitlijsten SET omroep_key = v_unknown_omroep WHERE omroep_key IS NULL;
  UPDATE public.staging_hitlijsten SET periode_key = v_unknown_periode WHERE periode_key IS NULL;
  UPDATE public.hitlijsten SET omroep_key = v_unknown_omroep WHERE omroep_key IS NULL;
  UPDATE public.hitlijsten SET periode_key = v_unknown_periode WHERE periode_key IS NULL;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'staging_hitlijsten_omroep_fk'
  ) THEN
    ALTER TABLE public.staging_hitlijsten
      ADD CONSTRAINT staging_hitlijsten_omroep_fk FOREIGN KEY (omroep_key) REFERENCES public.omroepen(omroep_key);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'staging_hitlijsten_periode_fk'
  ) THEN
    ALTER TABLE public.staging_hitlijsten
      ADD CONSTRAINT staging_hitlijsten_periode_fk FOREIGN KEY (periode_key) REFERENCES public.hitlijst_perioden(periode_key);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'hitlijsten_omroep_fk'
  ) THEN
    ALTER TABLE public.hitlijsten
      ADD CONSTRAINT hitlijsten_omroep_fk FOREIGN KEY (omroep_key) REFERENCES public.omroepen(omroep_key);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'hitlijsten_periode_fk'
  ) THEN
    ALTER TABLE public.hitlijsten
      ADD CONSTRAINT hitlijsten_periode_fk FOREIGN KEY (periode_key) REFERENCES public.hitlijst_perioden(periode_key);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS staging_hitlijsten_omroep_idx ON public.staging_hitlijsten(omroep_key);
CREATE INDEX IF NOT EXISTS staging_hitlijsten_periode_idx ON public.staging_hitlijsten(periode_key);
CREATE INDEX IF NOT EXISTS hitlijsten_omroep_idx ON public.hitlijsten(omroep_key);
CREATE INDEX IF NOT EXISTS hitlijsten_periode_idx ON public.hitlijsten(periode_key);
